/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RfDatePicker {
    }
    interface RfSelect {
    }
    interface RfSelectSearch {
    }
}
declare global {
    interface HTMLRfDatePickerElement extends Components.RfDatePicker, HTMLStencilElement {
    }
    var HTMLRfDatePickerElement: {
        prototype: HTMLRfDatePickerElement;
        new (): HTMLRfDatePickerElement;
    };
    interface HTMLRfSelectElement extends Components.RfSelect, HTMLStencilElement {
    }
    var HTMLRfSelectElement: {
        prototype: HTMLRfSelectElement;
        new (): HTMLRfSelectElement;
    };
    interface HTMLRfSelectSearchElement extends Components.RfSelectSearch, HTMLStencilElement {
    }
    var HTMLRfSelectSearchElement: {
        prototype: HTMLRfSelectSearchElement;
        new (): HTMLRfSelectSearchElement;
    };
    interface HTMLElementTagNameMap {
        "rf-date-picker": HTMLRfDatePickerElement;
        "rf-select": HTMLRfSelectElement;
        "rf-select-search": HTMLRfSelectSearchElement;
    }
}
declare namespace LocalJSX {
    interface RfDatePicker {
    }
    interface RfSelect {
    }
    interface RfSelectSearch {
    }
    interface IntrinsicElements {
        "rf-date-picker": RfDatePicker;
        "rf-select": RfSelect;
        "rf-select-search": RfSelectSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-date-picker": LocalJSX.RfDatePicker & JSXBase.HTMLAttributes<HTMLRfDatePickerElement>;
            "rf-select": LocalJSX.RfSelect & JSXBase.HTMLAttributes<HTMLRfSelectElement>;
            "rf-select-search": LocalJSX.RfSelectSearch & JSXBase.HTMLAttributes<HTMLRfSelectSearchElement>;
        }
    }
}
